name: jan_with_base
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    # UI
  pagination_view: ^2.0.0
  ant_icons: ^2.0.0-nullsafety.0
  cached_network_image: ^3.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.4.0



  # Network
  graphql_flutter: ^5.0.0
  internet_connection_checker: ^0.0.1+1

    # Dart data class
  json_serializable: ^6.2.0
  freezed_annotation: 0.14.2
  functional_enum_annotation: ^1.2.2

    # Dependency Injection
  get_it: ^7.1.3
  injectable: ^1.0.4

    # State management
  flutter_bloc: ^7.0.1

    # Caching
  hive: ^2.0.4
  shared_preferences: ^2.0.8


  # Misc
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.26.0
  path_provider: ^2.0.2

  cupertino_icons: ^1.0.2
  analyzer: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

    # Code generators
  freezed: ^0.14.2
  functional_enum: ^1.1.3
  injectable_generator: ^1.4.1
  build_runner: ^2.0.4

    # Linting
  effective_dart: ^1.3.1
  flutter_typeahead: ^3.2.4
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IranYekan
      fonts:
        - asset: fonts/iran_yekan_thin.ttf
          weight: 100
        - asset: fonts/iran_yekan_light.ttf
          weight: 200
        - asset: fonts/iran_yekan_regular.ttf
          weight: 300
        - asset: fonts/iran_yekan_medium.ttf
          weight: 400
        - asset: fonts/iran_yekan_bold.ttf
          weight: 500
        - asset: fonts/iran_yekan_black.ttf
          weight: 600
        - asset: fonts/iran_yekan_extra_bold.ttf
          weight: 700
        - asset: fonts/iran_yekan_extra_black.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
